# 04 - Hyperparameter Tuning With Optuna

This notebook runs a small hyperparameter tuning study on the saved training pseudobulks. It focuses on the architecture choices that matter most for the current MLP prototype: number of layers, number of neurons per layer, and dropout.

It uses Optuna's TPE sampler with pruning. That is a practical default for local deep-learning experiments: lighter than Ray, more efficient than a full grid, and easy to keep small.

In [1]:
from __future__ import annotations

import copy
import importlib.util
import json
import math
import random
from pathlib import Path
from typing import Sequence

REQUIRED_PACKAGES = {
    "numpy": "numpy",
    "optuna": "optuna",
    "pandas": "pandas",
    "matplotlib": "matplotlib",
    "torch": "torch",
}
missing_packages = [name for name, module in REQUIRED_PACKAGES.items() if importlib.util.find_spec(module) is None]
if missing_packages:
    raise ImportError(
        "Missing required packages: "
        + ", ".join(missing_packages)
        + ". Install the project environment first, for example with `uv sync`."
    )

import matplotlib.pyplot as plt
import numpy as np
import optuna
import pandas as pd
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "pyproject.toml").exists():
    raise RuntimeError("Run this notebook from the repository root, where pyproject.toml is located.")

REFERENCE_LABEL = "MLPDeconv_mouse"

REFERENCE_DIR = PROJECT_ROOT / "data" / "references" / REFERENCE_LABEL
PSEUDOBULK_DIR = REFERENCE_DIR / "pseudobulk"
HPO_DIR = REFERENCE_DIR / "hyperparameter_tuning"
HPO_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_SEED = 42
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# pin_memory speeds CPU-to-GPU batch transfer for DataLoaders when CUDA is available.
PIN_MEMORY = torch.cuda.is_available()
print(f"Device: {DEVICE}")

/home/sagemaker-user/user-default-efs/MLPDeconv/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Device: cuda

## Load Saved Pseudobulks

The tuning study only uses the training pseudobulks. A validation split is created inside this notebook. The held-out test pseudobulks stay untouched for final evaluation in notebook 02.

In [2]:
def load_pseudobulk_dataset(npz_path: str | Path) -> dict:
    path = Path(npz_path)
    if not path.exists():
        raise FileNotFoundError(f"Missing pseudobulk dataset: {path}. Run 01_create_pseudobulks.ipynb first.")
    with np.load(path, allow_pickle=True) as data:
        return {
            "X": data["X"].astype(np.float32),
            "y": data["y"].astype(np.float32),
            "genes": data["genes"].astype(str).tolist(),
            "cell_types": data["cell_types"].astype(str).tolist(),
            "sample_ids": data["sample_ids"].astype(str).tolist(),
        }


train_pseudobulk = load_pseudobulk_dataset(PSEUDOBULK_DIR / "train_pseudobulk.npz")
train_pb_X = train_pseudobulk["X"]
train_pb_y = train_pseudobulk["y"]
CELL_TYPES = train_pseudobulk["cell_types"]

print(f"Training pseudobulks: {train_pb_X.shape}")
print(f"Cell types: {len(CELL_TYPES)}")

Training pseudobulks: (20000, 23793)
Cell types: 15

## Preprocess Features

In [3]:
def normalize_bulk_counts(X: np.ndarray, scale_factor: float = 1_000_000.0) -> np.ndarray:
    X = np.asarray(X, dtype=np.float32)
    library_sizes = X.sum(axis=1, keepdims=True)
    if np.any(library_sizes <= 0):
        raise ValueError("At least one bulk sample has zero total counts and cannot be normalized.")
    normalized = (X / library_sizes) * scale_factor
    return np.log1p(normalized).astype(np.float32)


def split_train_validation(
    X: np.ndarray,
    y: np.ndarray,
    validation_fraction: float = 0.15,
    seed: int = RANDOM_SEED,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    indices = rng.permutation(X.shape[0])
    n_validation = int(round(X.shape[0] * validation_fraction))
    n_validation = max(1, min(X.shape[0] - 1, n_validation))
    validation_idx = indices[:n_validation]
    train_idx = indices[n_validation:]
    return X[train_idx], y[train_idx], X[validation_idx], y[validation_idx]


def fit_standardizer(X_train: np.ndarray, eps: float = 1e-6) -> tuple[np.ndarray, np.ndarray]:
    mean = X_train.mean(axis=0).astype(np.float32)
    std = X_train.std(axis=0).astype(np.float32)
    std[std < eps] = 1.0
    return mean, std


def apply_standardizer(X: np.ndarray, mean: np.ndarray, std: np.ndarray) -> np.ndarray:
    return ((X - mean) / std).astype(np.float32)


features_all = normalize_bulk_counts(train_pb_X)
X_train_raw, y_train, X_val_raw, y_val = split_train_validation(
    features_all,
    train_pb_y,
    validation_fraction=0.15,
    seed=RANDOM_SEED,
)
gene_mean, gene_std = fit_standardizer(X_train_raw)
X_train = apply_standardizer(X_train_raw, gene_mean, gene_std)
X_val = apply_standardizer(X_val_raw, gene_mean, gene_std)

print(f"X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"X_val:   {X_val.shape}, y_val:   {y_val.shape}")

X_train: (17000, 23793), y_train: (17000, 15)
X_val:   (3000, 23793), y_val:   (3000, 15)

## Model And Training Helpers

In [4]:
def set_reproducible_seed(seed: int = RANDOM_SEED) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


class BulkFractionDataset(Dataset):
    def __init__(self, X: np.ndarray, y: np.ndarray):
        self.X = torch.as_tensor(X, dtype=torch.float32)
        self.y = torch.as_tensor(y, dtype=torch.float32)

    def __len__(self) -> int:
        return self.X.shape[0]

    def __getitem__(self, index: int) -> tuple[torch.Tensor, torch.Tensor]:
        return self.X[index], self.y[index]


class MLPDeconvRegressor(nn.Module):
    def __init__(
        self,
        input_dim: int,
        output_dim: int,
        hidden_sizes: Sequence[int],
        dropout: float,
    ):
        super().__init__()
        layers: list[nn.Module] = []
        previous_dim = input_dim
        for hidden_dim in hidden_sizes:
            layers.append(nn.Linear(previous_dim, hidden_dim))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout))
            previous_dim = hidden_dim
        layers.append(nn.Linear(previous_dim, output_dim))
        self.network = nn.Sequential(*layers)

    def forward(self, X: torch.Tensor) -> torch.Tensor:
        return torch.softmax(self.network(X), dim=1)


@torch.no_grad()
def predict_array(model: nn.Module, X: np.ndarray, batch_size: int = 256, device: torch.device = DEVICE) -> np.ndarray:
    model.eval()
    tensor_dataset = torch.as_tensor(X, dtype=torch.float32)
    loader = DataLoader(tensor_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory=PIN_MEMORY)
    predictions = []
    for X_batch in loader:
        predictions.append(model(X_batch.to(device)).cpu().numpy())
    return np.vstack(predictions).astype(np.float32)


def rmse_score(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return float(np.sqrt(np.mean(np.square(y_pred - y_true))))


def validation_rmse(model: nn.Module, X_val: np.ndarray, y_val: np.ndarray, device: torch.device = DEVICE) -> float:
    predictions = predict_array(model, X_val, device=device)
    return rmse_score(y_val, predictions)

## Define The Search Space

This search uses the following hyperparameters: number of layers, base width, dropout, learning rate, weight decay, and batch size. Hidden layers follow a pyramid pattern by default: each layer is half the previous width, with a minimum width of 64 neurons.

In [5]:
def build_hidden_sizes(n_layers: int, base_width: int, min_width: int = 64) -> tuple[int, ...]:
    return tuple(max(min_width, base_width // (2 ** layer_idx)) for layer_idx in range(n_layers))


N_TRIALS = 50
MAX_STEPS_PER_TRIAL = 1500
VALIDATION_EVERY = 100
PATIENCE = 6

print("Optuna will tune:")
print("- n_layers: 1 to 3")
print("- base_width: 128, 256, 512, 1024, 2048")
print("- dropout: 0.0 to 0.4")
print("- learning_rate: 1e-5 to 3e-3, log scale")
print("- weight_decay: 1e-7 to 1e-2, log scale")
print("- batch_size: 32, 64, 128, 256")
print(f"Optuna trials configured: {N_TRIALS}")

Optuna will tune:
- n_layers: 1 to 3
- base_width: 128, 256, 512, 1024, 2048
- dropout: 0.0 to 0.4
- learning_rate: 1e-5 to 3e-3, log scale
- weight_decay: 1e-7 to 1e-2, log scale
- batch_size: 32, 64, 128, 256
Optuna trials configured: 50

## Run Optuna Study

In [6]:
def objective(trial: optuna.Trial) -> float:
    n_layers = trial.suggest_int("n_layers", 1, 3)
    base_width = trial.suggest_categorical("base_width", [128, 256, 512, 1024, 2048])
    dropout = trial.suggest_float("dropout", 0.0, 0.4, step=0.1)
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 3e-3, log=True)
    weight_decay = trial.suggest_float("weight_decay", 1e-7, 1e-2, log=True)
    batch_size = trial.suggest_categorical("batch_size", [32, 64, 128, 256])

    hidden_sizes = build_hidden_sizes(n_layers=n_layers, base_width=base_width)
    trial.set_user_attr("hidden_sizes", list(hidden_sizes))

    set_reproducible_seed(RANDOM_SEED + trial.number)
    train_loader = DataLoader(
        BulkFractionDataset(X_train, y_train),
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,
        pin_memory=PIN_MEMORY,
    )

    model = MLPDeconvRegressor(
        input_dim=X_train.shape[1],
        output_dim=y_train.shape[1],
        hidden_sizes=hidden_sizes,
        dropout=dropout,
    ).to(DEVICE)
    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=weight_decay)
    loss_fn = nn.MSELoss()

    best_rmse = math.inf
    best_state = copy.deepcopy(model.state_dict())
    checks_without_improvement = 0
    global_step = 0
    stop_training = False

    while global_step < MAX_STEPS_PER_TRIAL and not stop_training:
        model.train()
        for X_batch, y_batch in train_loader:
            X_batch = X_batch.to(DEVICE, non_blocking=PIN_MEMORY)
            y_batch = y_batch.to(DEVICE, non_blocking=PIN_MEMORY)
            optimizer.zero_grad(set_to_none=True)
            loss = loss_fn(model(X_batch), y_batch)
            loss.backward()
            optimizer.step()
            global_step += 1

            should_validate = global_step == 1 or global_step % VALIDATION_EVERY == 0 or global_step == MAX_STEPS_PER_TRIAL
            if should_validate:
                val_rmse = validation_rmse(model, X_val, y_val, device=DEVICE)
                trial.report(val_rmse, step=global_step)

                if val_rmse < best_rmse:
                    best_rmse = val_rmse
                    best_state = copy.deepcopy(model.state_dict())
                    checks_without_improvement = 0
                else:
                    checks_without_improvement += 1

                if trial.should_prune():
                    raise optuna.TrialPruned()
                if checks_without_improvement >= PATIENCE:
                    stop_training = True
                    break
            if global_step >= MAX_STEPS_PER_TRIAL:
                break

    model.load_state_dict(best_state)
    return best_rmse


sampler = optuna.samplers.TPESampler(seed=RANDOM_SEED)
pruner = optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=300, interval_steps=100)
study = optuna.create_study(direction="minimize", sampler=sampler, pruner=pruner)
study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=True)

print("Best validation RMSE:", study.best_value)
print("Best params:", study.best_params)
print("Best hidden sizes:", study.best_trial.user_attrs["hidden_sizes"])

[I 2026-07-06 20:00:22,277] A new study created in memory with name: no-name-b5550bef-26b7-4ab8-aa3c-7dcc871bfa08
Best trial: 0. Best value: 0.0199781:   2%|▏         | 1/50 [00:15<12:38, 15.48s/it]

[I 2026-07-06 20:00:37,754] Trial 0 finished with value: 0.019978100433945656 and parameters: {'n_layers': 2, 'base_width': 128, 'dropout': 0.0, 'learning_rate': 0.0013983740016490966, 'weight_decay': 0.00010129197956845733, 'batch_size': 128}. Best is trial 0 with value: 0.019978100433945656.

Best trial: 1. Best value: 0.0140989:   4%|▍         | 2/50 [00:44<18:44, 23.43s/it]

[I 2026-07-06 20:01:06,745] Trial 1 finished with value: 0.01409890316426754 and parameters: {'n_layers': 1, 'base_width': 1024, 'dropout': 0.1, 'learning_rate': 0.0003278187653397617, 'weight_decay': 4.982752357076448e-07, 'batch_size': 256}. Best is trial 1 with value: 0.01409890316426754.

Best trial: 1. Best value: 0.0140989:   6%|▌         | 3/50 [00:52<12:42, 16.23s/it]

[I 2026-07-06 20:01:14,414] Trial 2 finished with value: 0.19752196967601776 and parameters: {'n_layers': 1, 'base_width': 1024, 'dropout': 0.0, 'learning_rate': 0.0022413234378101127, 'weight_decay': 0.0067322489207753446, 'batch_size': 32}. Best is trial 1 with value: 0.01409890316426754.

Best trial: 1. Best value: 0.0140989:   8%|▊         | 4/50 [01:14<14:23, 18.77s/it]

[I 2026-07-06 20:01:37,068] Trial 3 finished with value: 0.01550686452537775 and parameters: {'n_layers': 2, 'base_width': 1024, 'dropout': 0.30000000000000004, 'learning_rate': 5.917607170144197e-05, 'weight_decay': 3.9841905944346885e-05, 'batch_size': 128}. Best is trial 1 with value: 0.01409890316426754.

Best trial: 1. Best value: 0.0140989:  10%|█         | 5/50 [01:27<12:19, 16.43s/it]

[I 2026-07-06 20:01:49,358] Trial 4 finished with value: 0.017521344125270844 and parameters: {'n_layers': 3, 'base_width': 512, 'dropout': 0.0, 'learning_rate': 6.395620370993665e-05, 'weight_decay': 8.777815504719654e-06, 'batch_size': 64}. Best is trial 1 with value: 0.01409890316426754.

Best trial: 1. Best value: 0.0140989:  12%|█▏        | 6/50 [01:50<13:40, 18.64s/it]

[I 2026-07-06 20:02:12,284] Trial 5 finished with value: 0.016075141727924347 and parameters: {'n_layers': 2, 'base_width': 1024, 'dropout': 0.0, 'learning_rate': 1.0319982330247679e-05, 'weight_decay': 0.0011948328168545441, 'batch_size': 128}. Best is trial 1 with value: 0.01409890316426754.

Best trial: 1. Best value: 0.0140989:  14%|█▍        | 7/50 [01:54<10:02, 14.00s/it]

[I 2026-07-06 20:02:16,747] Trial 6 pruned.

Best trial: 1. Best value: 0.0140989:  16%|█▌        | 8/50 [01:57<07:15, 10.36s/it]

[I 2026-07-06 20:02:19,314] Trial 7 pruned.

Best trial: 1. Best value: 0.0140989:  18%|█▊        | 9/50 [02:00<05:30,  8.07s/it]

[I 2026-07-06 20:02:22,329] Trial 8 pruned.

Best trial: 1. Best value: 0.0140989:  20%|██        | 10/50 [02:05<04:50,  7.26s/it]

[I 2026-07-06 20:02:27,784] Trial 9 pruned.

Best trial: 1. Best value: 0.0140989:  22%|██▏       | 11/50 [02:15<05:14,  8.05s/it]

[I 2026-07-06 20:02:37,634] Trial 10 pruned.

Best trial: 1. Best value: 0.0140989:  24%|██▍       | 12/50 [02:21<04:40,  7.38s/it]

[I 2026-07-06 20:02:43,475] Trial 11 pruned.

Best trial: 1. Best value: 0.0140989:  26%|██▌       | 13/50 [02:43<07:25, 12.05s/it]

[I 2026-07-06 20:03:06,273] Trial 12 pruned.

Best trial: 1. Best value: 0.0140989:  28%|██▊       | 14/50 [02:45<05:15,  8.76s/it]

[I 2026-07-06 20:03:07,413] Trial 13 pruned.

Best trial: 1. Best value: 0.0140989:  30%|███       | 15/50 [02:53<05:04,  8.71s/it]

[I 2026-07-06 20:03:16,025] Trial 14 pruned.

Best trial: 1. Best value: 0.0140989:  32%|███▏      | 16/50 [02:56<03:58,  7.02s/it]

[I 2026-07-06 20:03:19,132] Trial 15 pruned.

Best trial: 1. Best value: 0.0140989:  34%|███▍      | 17/50 [03:01<03:29,  6.33s/it]

[I 2026-07-06 20:03:23,861] Trial 16 pruned.

Best trial: 1. Best value: 0.0140989:  36%|███▌      | 18/50 [03:11<03:55,  7.37s/it]

[I 2026-07-06 20:03:33,646] Trial 17 pruned.

Best trial: 1. Best value: 0.0140989:  38%|███▊      | 19/50 [03:15<03:15,  6.32s/it]

[I 2026-07-06 20:03:37,511] Trial 18 pruned.

Best trial: 1. Best value: 0.0140989:  40%|████      | 20/50 [03:18<02:39,  5.33s/it]

[I 2026-07-06 20:03:40,537] Trial 19 pruned.

Best trial: 1. Best value: 0.0140989:  42%|████▏     | 21/50 [03:59<07:43, 16.00s/it]

[I 2026-07-06 20:04:21,404] Trial 20 finished with value: 0.015082389116287231 and parameters: {'n_layers': 2, 'base_width': 2048, 'dropout': 0.4, 'learning_rate': 4.795612481694089e-05, 'weight_decay': 5.465301586262062e-07, 'batch_size': 128}. Best is trial 1 with value: 0.01409890316426754.

Best trial: 1. Best value: 0.0140989:  44%|████▍     | 22/50 [04:39<10:55, 23.42s/it]

[I 2026-07-06 20:05:02,129] Trial 21 finished with value: 0.015165691263973713 and parameters: {'n_layers': 2, 'base_width': 2048, 'dropout': 0.4, 'learning_rate': 4.4453136315735375e-05, 'weight_decay': 5.304552817533731e-07, 'batch_size': 128}. Best is trial 1 with value: 0.01409890316426754.

Best trial: 1. Best value: 0.0140989:  46%|████▌     | 23/50 [05:20<12:53, 28.64s/it]

[I 2026-07-06 20:05:42,945] Trial 22 finished with value: 0.015283518470823765 and parameters: {'n_layers': 2, 'base_width': 2048, 'dropout': 0.4, 'learning_rate': 3.131409359498343e-05, 'weight_decay': 4.997007586343487e-07, 'batch_size': 128}. Best is trial 1 with value: 0.01409890316426754.

Best trial: 1. Best value: 0.0140989:  48%|████▊     | 24/50 [05:29<09:49, 22.66s/it]

[I 2026-07-06 20:05:51,646] Trial 23 pruned.

Best trial: 1. Best value: 0.0140989:  50%|█████     | 25/50 [05:37<07:38, 18.35s/it]

[I 2026-07-06 20:05:59,952] Trial 24 pruned.

Best trial: 1. Best value: 0.0140989:  52%|█████▏    | 26/50 [06:10<09:04, 22.67s/it]

[I 2026-07-06 20:06:32,694] Trial 25 pruned.

Best trial: 1. Best value: 0.0140989:  54%|█████▍    | 27/50 [06:53<10:59, 28.69s/it]

[I 2026-07-06 20:07:15,444] Trial 26 pruned.

Best trial: 1. Best value: 0.0140989:  56%|█████▌    | 28/50 [07:00<08:10, 22.30s/it]

[I 2026-07-06 20:07:22,827] Trial 27 pruned.

Best trial: 1. Best value: 0.0140989:  58%|█████▊    | 29/50 [07:02<05:41, 16.26s/it]

[I 2026-07-06 20:07:24,997] Trial 28 pruned.

Best trial: 1. Best value: 0.0140989:  60%|██████    | 30/50 [07:04<04:01, 12.05s/it]

[I 2026-07-06 20:07:27,230] Trial 29 pruned.

Best trial: 1. Best value: 0.0140989:  62%|██████▏   | 31/50 [07:47<06:43, 21.25s/it]

[I 2026-07-06 20:08:09,939] Trial 30 pruned.

Best trial: 1. Best value: 0.0140989:  64%|██████▍   | 32/50 [08:20<07:24, 24.69s/it]

[I 2026-07-06 20:08:42,671] Trial 31 pruned.

Best trial: 1. Best value: 0.0140989:  66%|██████▌   | 33/50 [08:55<07:53, 27.87s/it]

[I 2026-07-06 20:09:17,937] Trial 32 pruned.

Best trial: 1. Best value: 0.0140989:  68%|██████▊   | 34/50 [09:36<08:27, 31.72s/it]

[I 2026-07-06 20:09:58,643] Trial 33 finished with value: 0.015130418352782726 and parameters: {'n_layers': 2, 'base_width': 2048, 'dropout': 0.4, 'learning_rate': 4.640306970476025e-05, 'weight_decay': 2.4158472080320465e-07, 'batch_size': 128}. Best is trial 1 with value: 0.01409890316426754.

Best trial: 1. Best value: 0.0140989:  70%|███████   | 35/50 [10:17<08:36, 34.45s/it]

[I 2026-07-06 20:10:39,484] Trial 34 finished with value: 0.015028323978185654 and parameters: {'n_layers': 2, 'base_width': 2048, 'dropout': 0.4, 'learning_rate': 5.887655838382352e-05, 'weight_decay': 1.8950307838051856e-07, 'batch_size': 128}. Best is trial 1 with value: 0.01409890316426754.

Best trial: 1. Best value: 0.0140989:  72%|███████▏  | 36/50 [10:20<05:50, 25.02s/it]

[I 2026-07-06 20:10:42,492] Trial 35 pruned.

Best trial: 1. Best value: 0.0140989:  74%|███████▍  | 37/50 [10:27<04:16, 19.73s/it]

[I 2026-07-06 20:10:49,863] Trial 36 pruned.

Best trial: 1. Best value: 0.0140989:  76%|███████▌  | 38/50 [10:29<02:53, 14.49s/it]

[I 2026-07-06 20:10:52,133] Trial 37 pruned.

Best trial: 1. Best value: 0.0140989:  78%|███████▊  | 39/50 [10:41<02:28, 13.51s/it]

[I 2026-07-06 20:11:03,354] Trial 38 pruned.

Best trial: 1. Best value: 0.0140989:  80%|████████  | 40/50 [10:44<01:43, 10.34s/it]

[I 2026-07-06 20:11:06,298] Trial 39 pruned.

Best trial: 1. Best value: 0.0140989:  82%|████████▏ | 41/50 [10:49<01:19,  8.86s/it]

[I 2026-07-06 20:11:11,716] Trial 40 pruned.

Best trial: 1. Best value: 0.0140989:  84%|████████▍ | 42/50 [11:03<01:22, 10.37s/it]

[I 2026-07-06 20:11:25,590] Trial 41 pruned.

Best trial: 1. Best value: 0.0140989:  86%|████████▌ | 43/50 [11:43<02:15, 19.40s/it]

[I 2026-07-06 20:12:06,062] Trial 42 finished with value: 0.015186636708676815 and parameters: {'n_layers': 2, 'base_width': 2048, 'dropout': 0.4, 'learning_rate': 4.0961098619572594e-05, 'weight_decay': 3.470894207508203e-07, 'batch_size': 128}. Best is trial 1 with value: 0.01409890316426754.

Best trial: 1. Best value: 0.0140989:  88%|████████▊ | 44/50 [12:18<02:24, 24.10s/it]

[I 2026-07-06 20:12:41,117] Trial 43 pruned.

Best trial: 1. Best value: 0.0140989:  90%|█████████ | 45/50 [12:59<02:25, 29.02s/it]

[I 2026-07-06 20:13:21,636] Trial 44 finished with value: 0.014990825206041336 and parameters: {'n_layers': 2, 'base_width': 2048, 'dropout': 0.4, 'learning_rate': 6.0387227045180254e-05, 'weight_decay': 1.8581828587456483e-06, 'batch_size': 128}. Best is trial 1 with value: 0.01409890316426754.

Best trial: 1. Best value: 0.0140989:  92%|█████████▏| 46/50 [13:01<01:23, 20.94s/it]

[I 2026-07-06 20:13:23,729] Trial 45 pruned.

Best trial: 1. Best value: 0.0140989:  94%|█████████▍| 47/50 [13:15<00:56, 18.73s/it]

[I 2026-07-06 20:13:37,301] Trial 46 pruned.

Best trial: 1. Best value: 0.0140989:  96%|█████████▌| 48/50 [13:19<00:28, 14.41s/it]

[I 2026-07-06 20:13:41,632] Trial 47 pruned.

Best trial: 1. Best value: 0.0140989:  98%|█████████▊| 49/50 [13:22<00:10, 10.97s/it]

[I 2026-07-06 20:13:44,562] Trial 48 pruned.

Best trial: 1. Best value: 0.0140989: 100%|██████████| 50/50 [13:26<00:00, 16.12s/it]

[I 2026-07-06 20:13:48,300] Trial 49 pruned.
Best validation RMSE: 0.01409890316426754
Best params: {'n_layers': 1, 'base_width': 1024, 'dropout': 0.1, 'learning_rate': 0.0003278187653397617, 'weight_decay': 4.982752357076448e-07, 'batch_size': 256}
Best hidden sizes: [1024]

## Save Tuning Results

In [7]:
trial_rows = []
for trial in study.trials:
    trial_rows.append(
        {
            "trial": trial.number,
            "state": trial.state.name,
            "val_rmse": trial.value,
            "n_layers": trial.params.get("n_layers"),
            "base_width": trial.params.get("base_width"),
            "hidden_sizes": trial.user_attrs.get("hidden_sizes"),
            "dropout": trial.params.get("dropout"),
            "learning_rate": trial.params.get("learning_rate"),
            "weight_decay": trial.params.get("weight_decay"),
            "batch_size": trial.params.get("batch_size"),
        }
    )

trials_df = pd.DataFrame(trial_rows)
trials_path = HPO_DIR / "optuna_trials.csv"
best_config_path = HPO_DIR / "best_hyperparameters.json"
plot_path = HPO_DIR / "optuna_validation_rmse_by_trial.png"

trials_df.to_csv(trials_path, index=False)
best_config = {
    "objective": "validation_rmse",
    "best_value": study.best_value,
    "n_layers": study.best_params["n_layers"],
    "base_width": study.best_params["base_width"],
    "hidden_sizes": study.best_trial.user_attrs["hidden_sizes"],
    "dropout": study.best_params["dropout"],
    "learning_rate": study.best_params["learning_rate"],
    "weight_decay": study.best_params["weight_decay"],
    "batch_size": study.best_params["batch_size"],
    "fixed_training_parameters": {
        "max_steps_per_trial": MAX_STEPS_PER_TRIAL,
        "validation_every": VALIDATION_EVERY,
        "patience": PATIENCE,
        "loss": "MSE",
    },
}
best_config_path.write_text(json.dumps(best_config, indent=2), encoding="utf-8")

completed = trials_df[trials_df["state"] == "COMPLETE"].copy()
fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(completed["trial"], completed["val_rmse"], marker="o", linewidth=1.5)
ax.set_xlabel("Trial")
ax.set_ylabel("Validation RMSE")
ax.set_title("Optuna architecture and training-parameter search")
fig.tight_layout()
fig.savefig(plot_path, dpi=160, bbox_inches="tight")
plt.close(fig)

display(trials_df.sort_values("val_rmse", na_position="last"))
print(f"Saved trials to {trials_path}")
print(f"Saved best config to {best_config_path}")
print(f"Saved tuning plot to {plot_path}")
best_config

,trial,state,val_rmse,n_layers,base_width,hidden_sizes,dropout,learning_rate,weight_decay,batch_size
1,1,COMPLETE,0.014099,1,1024,[1024],0.1,0.000328,4.982752e-07,256
44,44,COMPLETE,0.014991,2,2048,"[2048, 1024]",0.4,0.000060,1.858183e-06,128
34,34,COMPLETE,0.015028,2,2048,"[2048, 1024]",0.4,0.000059,1.895031e-07,128
20,20,COMPLETE,0.015082,2,2048,"[2048, 1024]",0.4,0.000048,5.465302e-07,128
33,33,COMPLETE,0.015130,2,2048,"[2048, 1024]",0.4,0.000046,2.415847e-07,128
21,21,COMPLETE,0.015166,2,2048,"[2048, 1024]",0.4,0.000044,5.304553e-07,128
42,42,COMPLETE,0.015187,2,2048,"[2048, 1024]",0.4,0.000041,3.470894e-07,128
22,22,COMPLETE,0.015284,2,2048,"[2048, 1024]",0.4,0.000031,4.997008e-07,128
43,43,PRUNED,0.015352,2,2048,"[2048, 1024]",0.4,0.000032,1.132984e-03,128
3,3,COMPLETE,0.015507,2,1024,"[1024, 512]",0.3,0.000059,3.984191e-05,128
32,32,PRUNED,0.015669,2,2048,"[2048, 1024]",0.4,0.000026,5.418651e-07,128
30,30,PRUNED,0.015882,2,2048,"[2048, 1024]",0.3,0.000015,1.208741e-06,256
5,5,COMPLETE,0.016075,2,1024,"[1024, 512]",0.0,0.000010,1.194833e-03,128
26,26,PRUNED,0.016245,2,2048,"[2048, 1024]",0.2,0.000088,3.841787e-06,256
31,31,PRUNED,0.017080,2,2048,"[2048, 1024]",0.4,0.000036,5.756005e-07,128
25,25,PRUNED,0.017272,2,2048,"[2048, 1024]",0.4,0.000045,7.293683e-07,128
4,4,COMPLETE,0.017521,3,512,"[512, 256, 128]",0.0,0.000064,8.777816e-06,64
12,12,PRUNED,0.017835,2,1024,"[1024, 512]",0.3,0.000458,7.352836e-05,256
41,41,PRUNED,0.018827,2,2048,"[2048, 1024]",0.4,0.000053,8.554575e-07,128
0,0,COMPLETE,0.019978,2,128,"[128, 64]",0.0,0.001398,1.012920e-04,128
38,38,PRUNED,0.020059,2,2048,"[2048, 1024]",0.3,0.000078,1.004319e-05,128
6,6,PRUNED,0.021050,2,256,"[256, 128]",0.1,0.000064,4.446629e-04,64
46,46,PRUNED,0.021924,2,2048,"[2048, 1024]",0.3,0.000116,1.018938e-06,256
17,17,PRUNED,0.025142,3,1024,"[1024, 512, 256]",0.2,0.001132,2.219831e-04,256
40,40,PRUNED,0.025243,1,1024,[1024],0.0,0.000019,1.023932e-07,64
37,37,PRUNED,0.025605,1,256,[256],0.2,0.000050,5.150894e-06,64
36,36,PRUNED,0.027625,3,2048,"[2048, 1024, 512]",0.0,0.000069,1.836369e-07,32
8,8,PRUNED,0.028571,3,512,"[512, 256, 128]",0.1,0.000025,4.451314e-03,128
23,23,PRUNED,0.028869,3,2048,"[2048, 1024, 512]",0.4,0.000018,3.020464e-07,128
27,27,PRUNED,0.029274,3,2048,"[2048, 1024, 512]",0.1,0.000235,3.375633e-07,32
15,15,PRUNED,0.029313,2,256,"[256, 128]",0.3,0.000160,3.057926e-05,256
49,49,PRUNED,0.029640,2,256,"[256, 128]",0.3,0.000192,1.359741e-05,256
9,9,PRUNED,0.030251,1,1024,[1024],0.0,0.000037,1.366278e-05,64
48,48,PRUNED,0.031092,1,512,[512],0.4,0.000068,3.098444e-07,128
19,19,PRUNED,0.032024,2,128,"[128, 64]",0.1,0.000024,2.560247e-05,256
14,14,PRUNED,0.033218,2,2048,"[2048, 1024]",0.3,0.000652,9.149629e-07,128
47,47,PRUNED,0.035594,2,1024,"[1024, 512]",0.2,0.000343,1.674391e-07,64
13,13,PRUNED,0.037676,1,128,[128],0.2,0.000110,2.798326e-06,32
39,39,PRUNED,0.038114,3,512,"[512, 256, 128]",0.4,0.000149,2.518901e-07,128
7,7,PRUNED,0.041256,3,512,"[512, 256, 128]",0.2,0.000012,3.463037e-07,64
29,29,PRUNED,0.055458,2,128,"[128, 64]",0.4,0.000850,2.190752e-06,128
45,45,PRUNED,0.060082,2,128,"[128, 64]",0.4,0.001775,1.837077e-06,128
35,35,PRUNED,0.067231,2,512,"[512, 256]",0.3,0.002585,1.861577e-07,128
11,11,PRUNED,0.067926,1,1024,[1024],0.4,0.000233,1.690677e-06,256
18,18,PRUNED,0.077129,1,1024,[1024],0.3,0.000095,1.065693e-07,32
24,24,PRUNED,0.078797,1,2048,[2048],0.4,0.000131,1.393741e-06,128
28,28,PRUNED,0.093217,1,256,[256],0.3,0.000432,1.893188e-07,128
16,16,PRUNED,0.094379,1,1024,[1024],0.1,0.000251,5.369323e-06,128
10,10,PRUNED,0.128271,1,2048,[2048],0.4,0.000417,1.189700e-07,256
2,2,COMPLETE,0.197522,1,1024,[1024],0.0,0.002241,6.732249e-03,32

Saved trials to /mnt/custom-file-systems/efs/fs-0fb4188b34a49ecf4_fsap-0f622ffecc95fdbba/MLPDeconv/data/references/MLPDeconv_mouse/hyperparameter_tuning/optuna_trials.csv
Saved best config to /mnt/custom-file-systems/efs/fs-0fb4188b34a49ecf4_fsap-0f622ffecc95fdbba/MLPDeconv/data/references/MLPDeconv_mouse/hyperparameter_tuning/best_hyperparameters.json
Saved tuning plot to /mnt/custom-file-systems/efs/fs-0fb4188b34a49ecf4_fsap-0f622ffecc95fdbba/MLPDeconv/data/references/MLPDeconv_mouse/hyperparameter_tuning/optuna_validation_rmse_by_trial.png

{'objective': 'validation_rmse',
 'best_value': 0.01409890316426754,
 'n_layers': 1,
 'base_width': 1024,
 'hidden_sizes': [1024],
 'dropout': 0.1,
 'learning_rate': 0.0003278187653397617,
 'weight_decay': 4.982752357076448e-07,
 'batch_size': 256,
 'fixed_training_parameters': {'max_steps_per_trial': 1500,
  'validation_every': 100,
  'patience': 6,
  'loss': 'MSE'}}

## Use The Best Configuration

Copy the `hidden_sizes` and `dropout` from `best_hyperparameters.json` into `TrainingConfig` in `02_train_eval_model.ipynb`, then rerun notebook 02 for the final model and held-out test evaluation.

# Repeat for the Sub Celltype level

In [8]:
# Parameters

REFERENCE_LABEL = "mouse_sub"

ARTIFACT_DIR = PROJECT_ROOT / "data" / "artifacts"
PSEUDOBULK_DIR = ARTIFACT_DIR / "pseudobulk" / REFERENCE_LABEL
HPO_DIR = ARTIFACT_DIR / "hyperparameter_tuning" / REFERENCE_LABEL
HPO_DIR.mkdir(parents=True, exist_ok=True)

In [9]:
# Load Pseudobulk

train_pseudobulk = load_pseudobulk_dataset(PSEUDOBULK_DIR / "train_pseudobulk.npz")
train_pb_X = train_pseudobulk["X"]
train_pb_y = train_pseudobulk["y"]
CELL_TYPES = train_pseudobulk["cell_types"]

print(f"Training pseudobulks: {train_pb_X.shape}")
print(f"Cell types: {len(CELL_TYPES)}")

# Preprocess Features
features_all = normalize_bulk_counts(train_pb_X)
X_train_raw, y_train, X_val_raw, y_val = split_train_validation(
    features_all,
    train_pb_y,
    validation_fraction=0.15,
    seed=RANDOM_SEED,
)
gene_mean, gene_std = fit_standardizer(X_train_raw)
X_train = apply_standardizer(X_train_raw, gene_mean, gene_std)
X_val = apply_standardizer(X_val_raw, gene_mean, gene_std)

print(f"X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"X_val:   {X_val.shape}, y_val:   {y_val.shape}")

FileNotFoundError: Missing pseudobulk dataset: /mnt/custom-file-systems/efs/fs-0fb4188b34a49ecf4_fsap-0f622ffecc95fdbba/MLPDeconv/data/artifacts/pseudobulk/mouse_sub/train_pseudobulk.npz. Run 01_create_pseudobulks.ipynb first.

In [ ]:
# Run previously defined Optuna study

def objective(trial: optuna.Trial) -> float:
    n_layers = trial.suggest_int("n_layers", 1, 3)
    base_width = trial.suggest_categorical("base_width", [128, 256, 512, 1024, 2048])
    dropout = trial.suggest_float("dropout", 0.0, 0.4, step=0.1)
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 3e-3, log=True)
    weight_decay = trial.suggest_float("weight_decay", 1e-7, 1e-2, log=True)
    batch_size = trial.suggest_categorical("batch_size", [32, 64, 128, 256])

    hidden_sizes = build_hidden_sizes(n_layers=n_layers, base_width=base_width)
    trial.set_user_attr("hidden_sizes", list(hidden_sizes))

    set_reproducible_seed(RANDOM_SEED + trial.number)
    train_loader = DataLoader(
        BulkFractionDataset(X_train, y_train),
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,
        pin_memory=PIN_MEMORY,
    )

    model = MLPDeconvRegressor(
        input_dim=X_train.shape[1],
        output_dim=y_train.shape[1],
        hidden_sizes=hidden_sizes,
        dropout=dropout,
    ).to(DEVICE)
    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=weight_decay)
    loss_fn = nn.L1Loss()

    best_rmse = math.inf
    best_state = copy.deepcopy(model.state_dict())
    checks_without_improvement = 0
    global_step = 0
    stop_training = False

    while global_step < MAX_STEPS_PER_TRIAL and not stop_training:
        model.train()
        for X_batch, y_batch in train_loader:
            X_batch = X_batch.to(DEVICE, non_blocking=PIN_MEMORY)
            y_batch = y_batch.to(DEVICE, non_blocking=PIN_MEMORY)
            optimizer.zero_grad(set_to_none=True)
            loss = loss_fn(model(X_batch), y_batch)
            loss.backward()
            optimizer.step()
            global_step += 1

            should_validate = global_step == 1 or global_step % VALIDATION_EVERY == 0 or global_step == MAX_STEPS_PER_TRIAL
            if should_validate:
                val_rmse = validation_rmse(model, X_val, y_val, device=DEVICE)
                trial.report(val_rmse, step=global_step)

                if val_rmse < best_rmse:
                    best_rmse = val_rmse
                    best_state = copy.deepcopy(model.state_dict())
                    checks_without_improvement = 0
                else:
                    checks_without_improvement += 1

                if trial.should_prune():
                    raise optuna.TrialPruned()
                if checks_without_improvement >= PATIENCE:
                    stop_training = True
                    break
            if global_step >= MAX_STEPS_PER_TRIAL:
                break

    model.load_state_dict(best_state)
    return best_rmse

sampler = optuna.samplers.TPESampler(seed=RANDOM_SEED)
pruner = optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=300, interval_steps=100)
study = optuna.create_study(direction="minimize", sampler=sampler, pruner=pruner)
study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=True)

print("Best validation RMSE:", study.best_value)
print("Best params:", study.best_params)
print("Best hidden sizes:", study.best_trial.user_attrs["hidden_sizes"])

[I 2026-06-01 15:16:11,591] A new study created in memory with name: no-name-5914b99e-fd67-444d-964d-a0cac378e2f0
Best trial: 0. Best value: 0.0189985:   2%|▏         | 1/50 [00:05<04:10,  5.10s/it]

[I 2026-06-01 15:16:16,693] Trial 0 finished with value: 0.018998483195900917 and parameters: {'n_layers': 2, 'base_width': 128, 'dropout': 0.0, 'learning_rate': 0.0013983740016490966, 'weight_decay': 0.00010129197956845733, 'batch_size': 128}. Best is trial 0 with value: 0.018998483195900917.

Best trial: 1. Best value: 0.0132428:   4%|▍         | 2/50 [00:17<07:18,  9.14s/it]

[I 2026-06-01 15:16:28,665] Trial 1 finished with value: 0.013242784887552261 and parameters: {'n_layers': 1, 'base_width': 1024, 'dropout': 0.1, 'learning_rate': 0.0003278187653397617, 'weight_decay': 4.982752357076448e-07, 'batch_size': 256}. Best is trial 1 with value: 0.013242784887552261.

Best trial: 1. Best value: 0.0132428:   6%|▌         | 3/50 [00:20<04:59,  6.37s/it]

[I 2026-06-01 15:16:31,732] Trial 2 finished with value: 0.1990453600883484 and parameters: {'n_layers': 1, 'base_width': 1024, 'dropout': 0.0, 'learning_rate': 0.0022413234378101127, 'weight_decay': 0.0067322489207753446, 'batch_size': 32}. Best is trial 1 with value: 0.013242784887552261.

Best trial: 1. Best value: 0.0132428:   8%|▊         | 4/50 [00:29<05:55,  7.74s/it]

[I 2026-06-01 15:16:41,561] Trial 3 finished with value: 0.016506390646100044 and parameters: {'n_layers': 2, 'base_width': 1024, 'dropout': 0.30000000000000004, 'learning_rate': 5.917607170144197e-05, 'weight_decay': 3.9841905944346885e-05, 'batch_size': 128}. Best is trial 1 with value: 0.013242784887552261.

Best trial: 1. Best value: 0.0132428:  10%|█         | 5/50 [00:34<05:03,  6.75s/it]

[I 2026-06-01 15:16:46,554] Trial 4 finished with value: 0.01577545888721943 and parameters: {'n_layers': 3, 'base_width': 512, 'dropout': 0.0, 'learning_rate': 6.395620370993665e-05, 'weight_decay': 8.777815504719654e-06, 'batch_size': 64}. Best is trial 1 with value: 0.013242784887552261.

Best trial: 1. Best value: 0.0132428:  12%|█▏        | 6/50 [00:40<04:35,  6.26s/it]

[I 2026-06-01 15:16:51,876] Trial 5 pruned.

Best trial: 1. Best value: 0.0132428:  14%|█▍        | 7/50 [00:41<03:21,  4.68s/it]

[I 2026-06-01 15:16:53,300] Trial 6 pruned.

Best trial: 1. Best value: 0.0132428:  16%|█▌        | 8/50 [00:42<02:28,  3.53s/it]

[I 2026-06-01 15:16:54,373] Trial 7 pruned.

Best trial: 1. Best value: 0.0132428:  18%|█▊        | 9/50 [00:44<01:55,  2.82s/it]

[I 2026-06-01 15:16:55,639] Trial 8 pruned.

Best trial: 1. Best value: 0.0132428:  20%|██        | 10/50 [00:46<01:53,  2.83s/it]

[I 2026-06-01 15:16:58,485] Trial 9 pruned.

Best trial: 1. Best value: 0.0132428:  22%|██▏       | 11/50 [00:51<02:08,  3.30s/it]

[I 2026-06-01 15:17:02,860] Trial 10 pruned.

Best trial: 1. Best value: 0.0132428:  24%|██▍       | 12/50 [00:56<02:25,  3.82s/it]

[I 2026-06-01 15:17:07,873] Trial 11 pruned.

Best trial: 1. Best value: 0.0132428:  26%|██▌       | 13/50 [00:58<02:01,  3.29s/it]

[I 2026-06-01 15:17:09,942] Trial 12 pruned.

Best trial: 1. Best value: 0.0132428:  28%|██▊       | 14/50 [01:01<01:55,  3.20s/it]

[I 2026-06-01 15:17:12,928] Trial 13 pruned.

Best trial: 1. Best value: 0.0132428:  30%|███       | 15/50 [01:02<01:27,  2.50s/it]

[I 2026-06-01 15:17:13,809] Trial 14 pruned.

Best trial: 1. Best value: 0.0132428:  32%|███▏      | 16/50 [01:05<01:31,  2.70s/it]

[I 2026-06-01 15:17:16,970] Trial 15 pruned.

Best trial: 1. Best value: 0.0132428:  34%|███▍      | 17/50 [01:06<01:12,  2.20s/it]

[I 2026-06-01 15:17:18,008] Trial 16 pruned.

Best trial: 1. Best value: 0.0132428:  36%|███▌      | 18/50 [01:13<01:54,  3.58s/it]

[I 2026-06-01 15:17:24,799] Trial 17 pruned.

Best trial: 1. Best value: 0.0132428:  38%|███▊      | 19/50 [01:16<01:45,  3.40s/it]

[I 2026-06-01 15:17:27,782] Trial 18 pruned.

Best trial: 1. Best value: 0.0132428:  40%|████      | 20/50 [01:17<01:19,  2.67s/it]

[I 2026-06-01 15:17:28,737] Trial 19 pruned.

Best trial: 1. Best value: 0.0132428:  42%|████▏     | 21/50 [01:20<01:24,  2.91s/it]

[I 2026-06-01 15:17:32,205] Trial 20 pruned.

Best trial: 1. Best value: 0.0132428:  44%|████▍     | 22/50 [01:25<01:41,  3.64s/it]

[I 2026-06-01 15:17:37,551] Trial 21 pruned.

Best trial: 1. Best value: 0.0132428:  46%|████▌     | 23/50 [01:28<01:25,  3.18s/it]

[I 2026-06-01 15:17:39,674] Trial 22 pruned.

Best trial: 1. Best value: 0.0132428:  48%|████▊     | 24/50 [01:31<01:23,  3.19s/it]

[I 2026-06-01 15:17:42,890] Trial 23 pruned.

Best trial: 1. Best value: 0.0132428:  50%|█████     | 25/50 [01:33<01:09,  2.80s/it]

[I 2026-06-01 15:17:44,757] Trial 24 pruned.

Best trial: 1. Best value: 0.0132428:  52%|█████▏    | 26/50 [01:35<01:01,  2.57s/it]

[I 2026-06-01 15:17:46,799] Trial 25 pruned.

Best trial: 1. Best value: 0.0132428:  54%|█████▍    | 27/50 [01:42<01:28,  3.87s/it]

[I 2026-06-01 15:17:53,690] Trial 26 pruned.

Best trial: 1. Best value: 0.0132428:  56%|█████▌    | 28/50 [01:44<01:16,  3.50s/it]

[I 2026-06-01 15:17:56,321] Trial 27 pruned.

Best trial: 1. Best value: 0.0132428:  58%|█████▊    | 29/50 [01:47<01:06,  3.17s/it]

[I 2026-06-01 15:17:58,747] Trial 28 pruned.

Best trial: 1. Best value: 0.0132428:  60%|██████    | 30/50 [01:48<00:49,  2.49s/it]

[I 2026-06-01 15:17:59,639] Trial 29 pruned.

Best trial: 1. Best value: 0.0132428:  62%|██████▏   | 31/50 [01:52<00:56,  2.98s/it]

[I 2026-06-01 15:18:03,774] Trial 30 pruned.

Best trial: 1. Best value: 0.0132428:  64%|██████▍   | 32/50 [01:53<00:46,  2.60s/it]

[I 2026-06-01 15:18:05,486] Trial 31 pruned.

Best trial: 1. Best value: 0.0132428:  66%|██████▌   | 33/50 [01:55<00:37,  2.18s/it]

[I 2026-06-01 15:18:06,685] Trial 32 pruned.

Best trial: 1. Best value: 0.0132428:  68%|██████▊   | 34/50 [01:56<00:29,  1.83s/it]

[I 2026-06-01 15:18:07,709] Trial 33 pruned.

Best trial: 1. Best value: 0.0132428:  70%|███████   | 35/50 [01:58<00:28,  1.91s/it]

[I 2026-06-01 15:18:09,796] Trial 34 pruned.

Best trial: 1. Best value: 0.0132428:  72%|███████▏  | 36/50 [01:59<00:22,  1.59s/it]

[I 2026-06-01 15:18:10,628] Trial 35 pruned.

Best trial: 1. Best value: 0.0132428:  74%|███████▍  | 37/50 [02:01<00:22,  1.71s/it]

[I 2026-06-01 15:18:12,626] Trial 36 pruned.

Best trial: 1. Best value: 0.0132428:  76%|███████▌  | 38/50 [02:17<01:14,  6.22s/it]

[I 2026-06-01 15:18:29,373] Trial 37 finished with value: 0.01416042260825634 and parameters: {'n_layers': 3, 'base_width': 2048, 'dropout': 0.0, 'learning_rate': 2.4497441258908003e-05, 'weight_decay': 0.0003673859589974555, 'batch_size': 64}. Best is trial 1 with value: 0.013242784887552261.

Best trial: 1. Best value: 0.0132428:  78%|███████▊  | 39/50 [02:21<00:59,  5.42s/it]

[I 2026-06-01 15:18:32,924] Trial 38 pruned.

Best trial: 1. Best value: 0.0132428:  80%|████████  | 40/50 [02:24<00:48,  4.86s/it]

[I 2026-06-01 15:18:36,464] Trial 39 pruned.

Best trial: 1. Best value: 0.0132428:  82%|████████▏ | 41/50 [02:41<01:15,  8.41s/it]

[I 2026-06-01 15:18:53,165] Trial 40 finished with value: 0.01459785271435976 and parameters: {'n_layers': 3, 'base_width': 2048, 'dropout': 0.0, 'learning_rate': 3.0430239764674547e-05, 'weight_decay': 1.026380734819953e-07, 'batch_size': 64}. Best is trial 1 with value: 0.013242784887552261.

Best trial: 1. Best value: 0.0132428:  84%|████████▍ | 42/50 [02:52<01:14,  9.26s/it]

[I 2026-06-01 15:19:04,403] Trial 41 pruned.

Best trial: 1. Best value: 0.0132428:  86%|████████▌ | 43/50 [03:01<01:04,  9.20s/it]

[I 2026-06-01 15:19:13,451] Trial 42 pruned.

Best trial: 1. Best value: 0.0132428:  88%|████████▊ | 44/50 [03:10<00:54,  9.14s/it]

[I 2026-06-01 15:19:22,472] Trial 43 pruned.

Best trial: 1. Best value: 0.0132428:  90%|█████████ | 45/50 [03:14<00:37,  7.46s/it]

[I 2026-06-01 15:19:26,012] Trial 44 pruned.

Best trial: 1. Best value: 0.0132428:  92%|█████████▏| 46/50 [03:15<00:22,  5.55s/it]

[I 2026-06-01 15:19:27,100] Trial 45 pruned.

Best trial: 1. Best value: 0.0132428:  94%|█████████▍| 47/50 [03:19<00:14,  4.97s/it]

[I 2026-06-01 15:19:30,719] Trial 46 pruned.

Best trial: 1. Best value: 0.0132428:  96%|█████████▌| 48/50 [03:24<00:10,  5.22s/it]

[I 2026-06-01 15:19:36,510] Trial 47 pruned.

Best trial: 1. Best value: 0.0132428:  98%|█████████▊| 49/50 [03:30<00:05,  5.36s/it]

[I 2026-06-01 15:19:42,199] Trial 48 pruned.

Best trial: 1. Best value: 0.0132428: 100%|██████████| 50/50 [03:32<00:00,  4.25s/it]

[I 2026-06-01 15:19:44,085] Trial 49 pruned.
Best validation RMSE: 0.013242784887552261
Best params: {'n_layers': 1, 'base_width': 1024, 'dropout': 0.1, 'learning_rate': 0.0003278187653397617, 'weight_decay': 4.982752357076448e-07, 'batch_size': 256}
Best hidden sizes: [1024]

In [ ]:
# Save tunning results

trial_rows = []
for trial in study.trials:
    trial_rows.append(
        {
            "trial": trial.number,
            "state": trial.state.name,
            "val_rmse": trial.value,
            "n_layers": trial.params.get("n_layers"),
            "base_width": trial.params.get("base_width"),
            "hidden_sizes": trial.user_attrs.get("hidden_sizes"),
            "dropout": trial.params.get("dropout"),
            "learning_rate": trial.params.get("learning_rate"),
            "weight_decay": trial.params.get("weight_decay"),
            "batch_size": trial.params.get("batch_size"),
        }
    )

trials_df = pd.DataFrame(trial_rows)
trials_path = HPO_DIR / "optuna_trials.csv"
best_config_path = HPO_DIR / "best_hyperparameters.json"
plot_path = HPO_DIR / "optuna_validation_rmse_by_trial.png"

trials_df.to_csv(trials_path, index=False)
best_config = {
    "objective": "validation_rmse",
    "best_value": study.best_value,
    "n_layers": study.best_params["n_layers"],
    "base_width": study.best_params["base_width"],
    "hidden_sizes": study.best_trial.user_attrs["hidden_sizes"],
    "dropout": study.best_params["dropout"],
    "learning_rate": study.best_params["learning_rate"],
    "weight_decay": study.best_params["weight_decay"],
    "batch_size": study.best_params["batch_size"],
    "fixed_training_parameters": {
        "max_steps_per_trial": MAX_STEPS_PER_TRIAL,
        "validation_every": VALIDATION_EVERY,
        "patience": PATIENCE,
        "loss": "MSELoss",
    },
}
best_config_path.write_text(json.dumps(best_config, indent=2), encoding="utf-8")

completed = trials_df[trials_df["state"] == "COMPLETE"].copy()
fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(completed["trial"], completed["val_rmse"], marker="o", linewidth=1.5)
ax.set_xlabel("Trial")
ax.set_ylabel("Validation RMSE")
ax.set_title("Optuna architecture and training-parameter search")
fig.tight_layout()
fig.savefig(plot_path, dpi=160, bbox_inches="tight")
plt.close(fig)

display(trials_df.sort_values("val_rmse", na_position="last"))
print(f"Saved trials to {trials_path}")
print(f"Saved best config to {best_config_path}")
print(f"Saved tuning plot to {plot_path}")
best_config

,trial,state,val_rmse,n_layers,base_width,hidden_sizes,dropout,learning_rate,weight_decay,batch_size
1,1,COMPLETE,0.013243,1,1024,[1024],0.1,0.000328,4.982752e-07,256
37,37,COMPLETE,0.014160,3,2048,"[2048, 1024, 512]",0.0,0.000024,3.673860e-04,64
40,40,COMPLETE,0.014598,3,2048,"[2048, 1024, 512]",0.0,0.000030,1.026381e-07,64
4,4,COMPLETE,0.015775,3,512,"[512, 256, 128]",0.0,0.000064,8.777816e-06,64
41,41,PRUNED,0.015867,3,2048,"[2048, 1024, 512]",0.0,0.000026,1.302287e-07,64
47,47,PRUNED,0.015934,3,512,"[512, 256, 128]",0.0,0.000045,4.563255e-07,256
3,3,COMPLETE,0.016506,2,1024,"[1024, 512]",0.3,0.000059,3.984191e-05,128
42,42,PRUNED,0.016770,3,2048,"[2048, 1024, 512]",0.0,0.000017,3.510635e-07,64
43,43,PRUNED,0.017207,3,2048,"[2048, 1024, 512]",0.0,0.000038,2.175187e-07,64
5,5,PRUNED,0.017302,2,1024,"[1024, 512]",0.0,0.000010,1.194833e-03,128
17,17,PRUNED,0.017482,2,1024,"[1024, 512]",0.3,0.000343,7.903696e-05,256
30,30,PRUNED,0.017644,2,256,"[256, 128]",0.0,0.000117,1.043213e-04,256
21,21,PRUNED,0.017685,2,1024,"[1024, 512]",0.3,0.000056,3.410290e-05,128
11,11,PRUNED,0.017754,3,512,"[512, 256, 128]",0.1,0.000233,2.533989e-06,256
26,26,PRUNED,0.017764,3,1024,"[1024, 512, 256]",0.3,0.000075,3.369435e-06,256
0,0,COMPLETE,0.018998,2,128,"[128, 64]",0.0,0.001398,1.012920e-04,128
20,20,PRUNED,0.019479,2,256,"[256, 128]",0.0,0.000034,2.145087e-06,256
28,28,PRUNED,0.019522,2,512,"[512, 256]",0.2,0.000042,3.847680e-07,128
48,48,PRUNED,0.020037,3,2048,"[2048, 1024, 512]",0.0,0.000082,1.327584e-06,64
15,15,PRUNED,0.020964,3,512,"[512, 256, 128]",0.1,0.000729,5.516175e-06,256
6,6,PRUNED,0.021338,2,256,"[256, 128]",0.1,0.000064,4.446629e-04,64
25,25,PRUNED,0.021812,2,512,"[512, 256]",0.4,0.000111,2.614302e-04,128
44,44,PRUNED,0.023054,3,2048,"[2048, 1024, 512]",0.1,0.000064,1.032385e-07,64
27,27,PRUNED,0.023640,1,1024,[1024],0.1,0.000019,8.225726e-04,32
23,23,PRUNED,0.023838,1,1024,[1024],0.2,0.000052,6.023272e-05,128
9,9,PRUNED,0.023998,1,1024,[1024],0.0,0.000037,1.366278e-05,64
38,38,PRUNED,0.025294,3,2048,"[2048, 1024, 512]",0.2,0.000026,7.420272e-03,64
49,49,PRUNED,0.025449,3,256,"[256, 128, 64]",0.1,0.000156,2.059334e-07,256
46,46,PRUNED,0.025625,3,2048,"[2048, 1024, 512]",0.1,0.000013,4.367703e-06,64
31,31,PRUNED,0.025712,2,128,"[128, 64]",0.0,0.001951,2.097196e-05,128
45,45,PRUNED,0.026496,3,512,"[512, 256, 128]",0.0,0.000029,1.713871e-06,64
39,39,PRUNED,0.027090,3,2048,"[2048, 1024, 512]",0.1,0.000013,1.581948e-03,64
14,14,PRUNED,0.029326,2,256,"[256, 128]",0.1,0.000172,8.662897e-07,64
8,8,PRUNED,0.030136,3,512,"[512, 256, 128]",0.1,0.000025,4.451314e-03,128
33,33,PRUNED,0.030184,1,128,[128],0.0,0.000230,2.368589e-03,128
32,32,PRUNED,0.030561,2,128,"[128, 64]",0.0,0.002987,1.542196e-04,128
24,24,PRUNED,0.030924,2,1024,"[1024, 512]",0.3,0.000262,2.056187e-05,64
29,29,PRUNED,0.034037,2,128,"[128, 64]",0.0,0.000828,4.251184e-05,64
12,12,PRUNED,0.034184,3,128,"[128, 64, 64]",0.2,0.000458,1.105859e-06,256
34,34,PRUNED,0.036412,2,1024,"[1024, 512]",0.1,0.001315,4.518552e-04,128
16,16,PRUNED,0.038216,1,512,[512],0.0,0.000150,1.955480e-07,64
22,22,PRUNED,0.038328,3,1024,"[1024, 512, 256]",0.4,0.000019,1.826324e-04,128
19,19,PRUNED,0.040094,3,128,"[128, 64, 64]",0.3,0.000088,1.054109e-05,64
7,7,PRUNED,0.042910,3,512,"[512, 256, 128]",0.2,0.000012,3.463037e-07,64
35,35,PRUNED,0.044875,3,128,"[128, 64, 64]",0.0,0.001425,8.516225e-06,32
13,13,PRUNED,0.069756,1,2048,[2048],0.2,0.000110,6.091964e-06,32
10,10,PRUNED,0.089455,1,2048,[2048],0.4,0.000417,1.189700e-07,256
36,36,PRUNED,0.102170,1,1024,[1024],0.1,0.000576,1.765394e-05,128
18,18,PRUNED,0.180853,1,2048,[2048],0.1,0.000849,7.259694e-07,32
2,2,COMPLETE,0.199045,1,1024,[1024],0.0,0.002241,6.732249e-03,32

Saved trials to /mnt/custom-file-systems/efs/fs-0fb4188b34a49ecf4_fsap-0f622ffecc95fdbba/MLPDeconv/data/artifacts/hyperparameter_tuning/mouse_sub/optuna_trials.csv
Saved best config to /mnt/custom-file-systems/efs/fs-0fb4188b34a49ecf4_fsap-0f622ffecc95fdbba/MLPDeconv/data/artifacts/hyperparameter_tuning/mouse_sub/best_hyperparameters.json
Saved tuning plot to /mnt/custom-file-systems/efs/fs-0fb4188b34a49ecf4_fsap-0f622ffecc95fdbba/MLPDeconv/data/artifacts/hyperparameter_tuning/mouse_sub/optuna_validation_rmse_by_trial.png

{'objective': 'validation_rmse',
 'best_value': 0.013242784887552261,
 'n_layers': 1,
 'base_width': 1024,
 'hidden_sizes': [1024],
 'dropout': 0.1,
 'learning_rate': 0.0003278187653397617,
 'weight_decay': 4.982752357076448e-07,
 'batch_size': 256,
 'fixed_training_parameters': {'max_steps_per_trial': 1500,
  'validation_every': 100,
  'patience': 6,
  'loss': 'MSELoss'}}